export interface wineState{
    winePid:number;
    wineImageUrl?:number;
    wineKorName:string;
    wineEngName?:string;
    winePrice?:string;
    wineType?:string;
    winebody?:number;
    wineAcidity?:number;
    wineTannin?:number;
    wineSweet?:number;
    wineAlcohol?:string;
    wineCountry?:string;
    wineRegion?:string;
    wineDesc?:string;
    wineStarPoint?:number;
    wineRecommendedSnack?:string;
    wineGrapeVariety?:string;
    userLike:boolean;
  }